.github/workflows/Spring CI.yml
src/main/resources/application.yml
src/main/resources/static/index.html

PR 시 테스트 코드 검사 및 의존성 취약점 검사
PR 시 테스트 코드 실행 및 의존성 관련 취약점 검사를 위한 Actions 파일입니다.
이 파일이 병합되면  PR을 진행할 때 마다 위 내용에 대한 검사가 실행됩니다.
- 📚 CI 자동화 내용 추가
위 내용은 개인 Repository에서 테스트 한 결과입니다.
#3 [Feat] 프로젝트 CI/CD 세팅
- DB 연동이 필요한 테스트 코드는 Entity 설계와 DB 서버를 올린 후 보안 관련사안에 대해 Secret Action을 통해 추가 적용할 예정입니다.

PR 시 테스트 코드, 의존성 취약점 검사 자동화

---

src/main/java/org/example/spring/domain/review/Review.java

Review 엔티티 구현
- ✨ (새 기능)
- 🐛 (버그 수정)
- ♻️ (리팩토링)
- 📚 (문서 업데이트)
- 🔧 (설정 파일 수정)
- ⚡️ (성능 개선)

Feat: Review 엔티티 구현

---

src/main/java/org/example/spring/constants/SalesStatus.java
src/main/java/org/example/spring/domain/exchange/Exchange.java
src/main/java/org/example/spring/domain/exchangeImage/ExchangeImage.java
src/main/java/org/example/spring/domain/like/Like.java
src/main/java/org/example/spring/domain/likeOverview/LikeOverview.java
src/main/java/org/example/spring/domain/review/Review.java
src/main/java/org/example/spring/domain/reviewImage/ReviewImage.java
src/main/java/org/example/spring/domain/reviewOverview/ReviewOverview.java

Exchange 엔티티 구현
ExchangeImage 엔티티 구현
Like 엔티티 구현
LikeOverview 엔티티 구현
ReviewImage 엔티티 구현
ReviewOverview 엔티티 구현
- ✨ Exchange 엔티티 구현
- ✨ ExchangeImage 엔티티 구현
- ✨ Like 엔티티 구현
- ✨ LikeOverview 엔티티 구현
- ✨ ReviewImage 엔티티 구현
- ✨ ReviewOverview 엔티티 구현
- ♻️ Review 엔티티 변수명 CamelCase 적용

Feat: Exchange, ExchangeImage, Like, LikeOverview, ReviewImage, ReviewOverview 엔티티 구현

---

src/main/java/org/example/spring/domain/exchange/Exchange.java
src/main/java/org/example/spring/domain/like/Like.java
src/main/java/org/example/spring/domain/review/Review.java
src/main/java/org/example/spring/domain/reviewOverview/ReviewOverview.java

import 문 오류로 인한 엔티티 수정
- 🐛 Exchange 엔티티 수정
- 🐛 Like 엔티티 수정
- 🐛 Review 엔티티 수정
- 🐛 ReviewOverview 엔티티 수정
Closes #21

Fix: Exchange, Like, Review, ReviewOverview 엔티티 수정

---

src/main/java/org/example/spring/Application.java
src/main/java/org/example/spring/audit/Auditable.java
src/main/java/org/example/spring/domain/message/Message.java
src/main/java/org/example/spring/domain/message/MessageMember.java
src/main/java/org/example/spring/domain/message/MessageRoom.java

Message, MessageRoom, MessageMember 엔티티 구현
- ✨ (새 기능)
- 🐛 (버그 수정)
- ♻️ (리팩토링)
- 📚 (문서 업데이트)
- 🔧 (설정 파일 수정)
- ⚡️ (성능 개선)

Feat: Message 엔티티 구현 #14

---

src/main/java/org/example/spring/repository/MemberRepository.java
src/test/java/org/example/spring/repository/MemberRepositoryTest.java

MemberRepository 인터페이스 구현 및 테스트코드 작성
- ✨ (새 기능) MemberRepository 인터페이스 추가
- ✅ MemberRepository에 대한 테스트 코드 작성
- MemberRepositoryTest에서 회원 저장, ID로 회원 찾기, 이메일/닉네임/전화번호 존재 여부 확인 테스트를 추가했습니다.
- 회원 가입 API를 호출하여 회원이 정상적으로 등록되는지 확인했습니다.
N/A
Relates to #23 
테스트 코드에서 누락된 부분이나 개선할 점이 있다면 피드백 부탁드립니다.

Feat: MemberRepository 구현

---

src/main/java/org/example/spring/security/SecurityConfig.java

스프링 시큐리티 기본 설정 구현
- ✨ SecurityFilterChain 설정 추가
- ✨ PasswordEncoder 빈 정의
- ✨ 역할 계층 구조 설정 (ADMIN > USER)
- 🔧 CSRF 보호 임시 비활성화 (추후 토큰 발행으로 대체 예정)
- ✨ 기본 로그인 폼 및 HTTP Basic 인증 활성화
N/A
Closes #34 
N/A

Feat: Spring Security 기본 설정 구현

---

.github/workflows/Spring CI.yml

CI 설정에 MySQL 연동 추가
- 🔧MySQL 연동 추가
N/A
Closes #37 
N/A

chore: CI 설정에 MySQL 연동 추가

---

build.gradle
src/main/java/org/example/spring/audit/Auditable.java
src/main/java/org/example/spring/domain/message/Message.java
src/main/java/org/example/spring/domain/message/MessageMember.java
src/main/java/org/example/spring/domain/message/MessageRoom.java
src/main/java/org/example/spring/domain/message/messageDto/MessageMemberRequestDto.java
src/main/java/org/example/spring/domain/message/messageDto/MessageMemberResponseDto.java
src/main/java/org/example/spring/domain/message/messageDto/MessageRequestDto.java
src/main/java/org/example/spring/domain/message/messageDto/MessageResponseDto.java
src/main/java/org/example/spring/domain/message/messageDto/MessageRoomRequestDto.java
src/main/java/org/example/spring/domain/message/messageDto/MessageRoomResponseDto.java

Message, MessageRoom, MessageMember DTO 구현
Message, MessageRoom, MessageMember DTO 구현
- ✨ (새 기능)
- 🐛 (버그 수정)
- ♻️ (리팩토링)
- 📚 (문서 업데이트)
- 🔧 (설정 파일 수정)
- ⚡️ (성능 개선)

Feat: Message DTO 구현 #31

---

src/main/java/org/example/spring/domain/member/dto/MemberJoinRequestDto.java
src/main/java/org/example/spring/service/MemberService.java
src/test/java/org/example/spring/service/MemberServiceTest.java

MemberService를 구현합니다. 회원 등록, 유효성 검사, 중복 검사 등의 기능을 포함하고 있습니다.
- ✨ MemberService 클래스 구현
- 회원 등록 (registerMember) 메서드 추가
- 회원 정보 유효성 검사 로직 구현
- 중복 회원 검사 로직 구현
- MemberField 열거형 추가로 회원 정보 필드 관리
- 📚 MemberJoinRequestDto 클래스 추가
- 🔧 PasswordEncoder를 이용한 비밀번호 암호화 로직 구현
- MemberServiceTest 클래스 생성 및 테스트 케이스 구현
N/A
Relates to #23 
N/A

Feat: MemberService 회원 등록 기능 구현

---

src/main/java/org/example/spring/controller/ExchangeController.java
src/main/java/org/example/spring/domain/exchange/Exchange.java
src/main/java/org/example/spring/domain/exchange/dto/ExchangeModifyRequestDto.java
src/main/java/org/example/spring/domain/exchange/dto/ExchangeRequestDto.java
src/main/java/org/example/spring/domain/exchange/dto/ExchangeResponseDto.java
src/main/java/org/example/spring/repository/ExchangeRepository.java
src/main/java/org/example/spring/service/ExchangeService.java

exchange crud api 구현
- ✨ (새 기능) 중고거래 게시판 생성
Closes #24

 Feat: exchange CRUD 구현

---

src/main/java/org/example/spring/domain/member/dto/MemberJoinRequestDto.java
src/main/java/org/example/spring/domain/member/dto/MemberResponseDto.java
src/main/java/org/example/spring/service/MemberService.java
src/test/java/org/example/spring/repository/MemberRepositoryTest.java
src/test/java/org/example/spring/service/MemberServiceTest.java

MemberService 관련 전반적인 코드 리펙터링
- ♻️ MemberService Validation 관련 로직 삭제
- ♻️ MemberJoinDto에 Bean Validation 어노테이션 추가
- ♻️ MemberServiceTest 코드 변경
N/A
Closes #51

Refactor/#51 MemberService 코드 리펙터링

---

src/main/java/org/example/spring/common/GlobalExceptionHandler.java
src/main/java/org/example/spring/controller/MemberController.java
src/main/java/org/example/spring/domain/member/dto/MemberJoinRequestDto.java
src/main/java/org/example/spring/domain/member/dto/MemberResponseDto.java
src/main/java/org/example/spring/service/MemberService.java
src/test/java/org/example/spring/controller/MemberControllerTest.java
src/test/java/org/example/spring/repository/MemberRepositoryTest.java
src/test/java/org/example/spring/service/MemberServiceTest.java

MemberController 코드 리펙터링
- ♻️ MemberController 의 ExceptionHandler 관련 로직 GlobalExceptionHandler 클래스로 분리
N/A
Closes #53

Refactor/#53 MemberController 코드 리펙터링

---

src/main/java/org/example/spring/domain/exchangeImage/ExchangeImage.java
src/main/java/org/example/spring/domain/like/Like.java
src/main/java/org/example/spring/domain/likeOverview/LikeOverview.java
src/main/java/org/example/spring/domain/message/MessageMember.java
src/main/java/org/example/spring/domain/message/MessageRoom.java
src/main/java/org/example/spring/domain/review/Review.java
src/main/java/org/example/spring/domain/reviewImage/ReviewImage.java
src/main/java/org/example/spring/domain/reviewOverview/ReviewOverview.java

테이블 명을 스네이크 케이스로 수정
- 🐛 테이블 명을 스네이크 케이스로 수정
Closes #55

Fix: 엔티티 테이블명 수정

---

src/main/java/org/example/spring/common/GlobalExceptionHandler.java
src/test/java/org/example/spring/controller/MemberControllerTest.java

GlobalExceptionHandler BAD_REQUEST 메세지 수정
- ♻️  관련 테스트코드 수정
Closes #57

Refactor: GlobalExceptionHandler BAD_REQUEST 메세지 수정

---

src/main/java/org/example/spring/repository/MemberRepository.java
src/main/java/org/example/spring/security/CustomUserDetailsService.java
src/main/java/org/example/spring/security/CustomeUsernamePasswordAuthenticationProvider.java

이메일을 사용한 사용자 세부 정보 로드 및 인증 처리 기능을 구현했습니다.
- ✨ 사용자 이메일을 이용한 사용자 정보 조회 기능 추가
- ✨ 사용자 아이디/비밀번호를 이용한 인증 처리 기능 구현
Relates to #59

Feat/#59 사용자 세부 정보 로드 및 인증 처리 기능 구현

---

src/main/java/org/example/spring/controller/ExchangeController.java
src/main/java/org/example/spring/service/ExchangeService.java
src/test/java/org/example/spring/controller/ExchangeControllerTest.java
src/test/java/org/example/spring/repository/ExchangeRepositoryTest.java
src/test/java/org/example/spring/service/ExchangeServiceTest.java

구현되어 있는 ExchangeRepository, ExchangeService, ExchangeController에 대한 테스트 코드를 작성했습니다.
- ✨ ExchangeRepository 테스트 코드 작성
- ✨ ExchangeService 테스트 코드 작성
- ✨ ExchangeController 테스트 코드 작성
Relates #46
없음

Feat: Exchange 관련 Class 테스트 코드 작성

---

src/main/java/org/example/spring/security/CustomUserDetailsService.java
src/main/java/org/example/spring/security/CustomUsernamePasswordAuthenticationProvider.java
src/test/java/org/example/spring/security/CustomUserDetailsServiceTest.java
src/test/java/org/example/spring/security/CustomUsernamePasswordAuthenticationProviderTest.java

사용자 세부 정보 로드 및 인증 처리 기능 관련 테스트 코드를 추가했습니다. 또한, 관련 클래스들에 JavaDoc을 추가하여 코드 문서화를 개선했습니다.
- ✨ CustomeUsernamePasswordAuthenticationProvider 및 CustomUserDetailsService에 대한 단위 테스트 추가
- 📚 Spring Security 관련 클래스들에 JavaDoc 추가
- ♻️ Mockito 사용 시 리소스 관리 개선
- 
- CustomeUsernamePasswordAuthenticationProviderTest 추가
- CustomUserDetailsServiceTest 추가
- 추가된 단위 테스트 실행 및 결과 확인
Closes #59

Feat: 사용자 세부 정보 로드 및 인증 처리 기능 관련 테스트 코드 추가

---

.github/workflows/FE CD.yml
fe/play-baseball-fe/constants/endpoints.tsx
fe/play-baseball-fe/next.config.mjs
fe/play-baseball-fe/package-lock.json
fe/play-baseball-fe/pages/result/index.tsx
fe/play-baseball-fe/pages/result/result-page.tsx
fe/play-baseball-fe/pages/signup/index.tsx
src/main/java/org/example/spring/domain/exchange/Exchange.java
src/main/java/org/example/spring/global/WebConfig.java
src/main/java/org/example/spring/repository/ReviewRepository.java
src/test/java/org/example/spring/repository/ExchangeRepositoryTest.java

작업 중 실수로 인해 3가지 이슈를 하나의 Branch에서 작업했습니다.
프로젝트에 속해있는 FE 영역에 대한 내용을 AWS에 설치한 서버로 자동으로 배포할 수 있는 환경을 구축했습니다.
자동 배포는 main Branch에 Merge 되었을 때 작동합니다.
API 문서에 따른 로그인 기능을 추가했습니다.
Java 파일 수정 내용이 없었으나 갑작스럽게 CI가 통과하지 못하는 현상이 발견되어 이를 수정했습니다.
- ✨ FE CD.yml 파일 작성 (자동 배포 관련 GitHub Actions 파일)
- ✨ FE 전용 AWS Instance 작업
- ✨ CORS 에러 수정을 위해 WebConfig.java 파일 추가
- 📚 next.config.js 파일 내용을 기존 작성된 DockerFile에 맞출 수 있도록 업데이트
- 📚 Repository 내 Secrets 문서에 FE 서버 관련 내용 추가(FE_KEY, FE_HOST)
- 🔧 npm install 후 package-lock.json 파일 동기화
- ✨ 회원가입 기능 페이지에서 구현
- ✨ API 문서 목록 상수화 코드 작성
- ✨ 결과 페이지 레이아웃 및 기능 작성
- ✨ ExchangeRepositoryTest 재작성
- ✨ ReviewRepository 파일 추가(메서드 내용 비어있음)
- ✨ Exchange Entity 내용 중 Review와 관계 매핑 부분 추가
Relates to #67
Relates to #64
Relates to #44
Notion의 환경 변수 목록, 서버 연결 방법 페이지에 내용 추가되었습니다.
FE 서버 Instance를 한 …

Feat: FE 영역 자동 배포 기능 작업, 회원가입 페이지 API 연결, Exchange 관련 테스트 코드 내용 수정

---

.github/workflows/Spring CI.yml

Spring CI.yml 에 JWT 관련 환경변수 추가
- 🔧 JWT 관련 환경변수 추가
Relates to #63

Chore: Spring CI.yml 에 JWT 관련 환경변수 추가

---

build.gradle
src/main/java/org/example/spring/controller/AuthController.java
src/main/java/org/example/spring/controller/MemberController.java
src/main/java/org/example/spring/domain/member/dto/LoginRequestDto.java
src/main/java/org/example/spring/security/CustomAccessDeniedHandler.java
src/main/java/org/example/spring/security/CustomAuthenticationEntryPoint.java
src/main/java/org/example/spring/security/SecurityConfig.java
src/main/java/org/example/spring/security/jwt/CookieService.java
src/main/java/org/example/spring/security/jwt/JwtAuthenticationService.java
src/main/java/org/example/spring/security/jwt/JwtTokenProvider.java
src/main/java/org/example/spring/security/jwt/JwtTokenValidator.java
src/main/java/org/example/spring/security/jwt/JwtUtils.java
src/main/java/org/example/spring/security/jwt/JwtValidatorFilter.java
src/main/java/org/example/spring/service/AuthService.java
src/main/resources/application.yml

JWT 기반 인증 시스템을 구현하고 Spring Security 설정을 개선했습니다.
- ✨ JWT 관련 클래스 구현 (JwtUtils, JwtTokenProvider, JwtTokenValidator, JwtAuthenticationService, JwtValidatorFilter)
- ✨ CookieService 구현으로 쿠키 관리 기능 추가
- ✨ CustomAuthenticationEntryPoint 및 CustomAccessDeniedHandler 구현으로 인증/인가 예외 처리 개선
- 🔧 application.yml에 JWT 관련 설정 추가
- 🔧 build.gradle에 JWT 의존성 추가
- ✨ LoginRequestDto 추가 및 MemberController에 로그인 기능 구현
- ♻️ SecurityConfig 리팩토링 및 JWT 기반 인증 적용
- 🐛 토큰 갱신 로직 수정 및 보안 강화
- ✨ AuthService 구현으로 인증 로직 분리
- 💄 시간 표현 방식을 LocalDateTime에서 Instant로 변경하여 국제 표준 준수
- JWT 액세스 토큰 발행 테스트
- 리프레시 토큰 발행 테스트
- 액세스 토큰 변조 시 접근 거부 확인
Closes #63 
- JWT 비밀 키와 만료 시간은 환경 변수로 설정했습니다.
- access token 은 응답 본문에 포함되어있습니다.
- refresh token 은 HTTP ONLY 쿠키에 포함되어있습니다.
- 성능 테스트를 통해 JWT 검증이 시스템에 미치는 영향을 확인해볼 필요가 있습니다.

Feat: JWT 기반 인증 시스템을 구현

---

src/main/java/org/example/spring/security/config/SecurityConfig.java

CORS 설정 최적화 및 강화
- ✨ CORS 설정 최적화 및 강화
Relates to #74

Feat: SecurityConfig CORS 설정 강화

---

.github/workflows/FE CD.yml
.github/workflows/Spring CD.yml
.github/workflows/Spring CI.yml

배포 환경을 만들었으나, pr 후 바로 확인이 어려운 환경으로 인해 dev에 push 되었을 때도 작동하도록 CD 환경을 수정했습니다.
- 🔧 FE, BE CD dev 환경에서 작동하도록 수정
- 🔧 CI 코드 정렬
Relates #69

Chore: dev 환경에서 CD 작동하도록 수정

---

src/main/java/org/example/spring/security/config/SecurityConfig.java

SecurityConfig Cors 오리진 주소 변경
- ♻️ setAllowedOrigins 수정
Relates to #74

Refactor: SecurityConfig Cors 오리진 변경

---

fe/play-baseball-fe/constants/endpoints.tsx

Request URL 주소에 http 부분을 추가합니다.
- ♻️ REQUEST  URL 내용 수정

Refactor: REQUEST_URL 주소 수정

---

src/main/java/org/example/spring/security/jwt/CookieService.java

CookieService refreshToken 생성시 sameSite 속성 설정
- ✨ refreshToken 생성시 samSite 속성 추가로 CSRF 공격 방지 
- ✨ Lax 설정 사용으로 일반적인 크로스 사이트 탐색 허용
Closes #74

Feat: CookieService refreshToken 생성시 sameSite 속성 설정

---

fe/play-baseball-fe/pages/login/index.tsx

로그인 페이지 버튼 클릭 시 API를 호출하는 코드를 업데이트했습니다.
로그인 성공 시 main page로 이동합니다.
- ✨ 로그인 페이지 버튼 기능 구현
Relate #81

Feat: 로그인 페이지 API 연결

---

src/main/java/org/example/spring/security/config/SecurityDevConfig.java
src/test/java/org/example/spring/repository/MemberRepositoryTest.java

SecurityConfig 개발 환경 배포 환경 분리
- ✨ 개발환경 배포환경 분리
Closes #88

Feat: SecurityConfig 환경 분리

---

src/main/java/org/example/spring/controller/AuthController.java

AuthController APi 앤드포인트 수정
- 🐛 AuthController APi 앤드포인트 수정
Closes #91

Fix: AuthController APi 앤드포인트 수정

---

fe/play-baseball-fe/pages/exchange/write/index.tsx

게시글 작성 페이지 레이아웃을 추가했습니다.
- 💄 게시글 작성 페이지 레이아웃 추가
- ✨ 이미지 첨부 기능
Relates #81

Feat: 게시글 작성 페이지 레이아웃

---

src/main/java/org/example/spring/controller/AuthController.java

AuthController APi 앤드포인트 수정
- ♻️ AuthController APi 앤드포인트 수정 /api/members -> /api/auth
Closes #94

Refactor: AuthController APi 앤드포인트 수정

---

fe/play-baseball-fe/pages/chat/[id].js
fe/play-baseball-fe/pages/chat/index.tsx

채팅 기능을 FE에서 구현하기 위해 우선 레이아웃을 작업했습니다.
- ✨ 채팅 보내기
- ✨ 안 읽은 메세지 표시
- 💄 사용중인 채팅창 강조
- 💄 채팅방 목록 레이아웃
- 💄 1:1 채팅 내역 레이아웃
Relates to #104

Feat: 채팅방 페이지 레이아웃 작성

---

fe/play-baseball-fe/constants/endpoints.tsx

합의에 따라 로그인, 로그아웃 api 경로가 변경되어 이를 수정합니다.
- ♻️ endpoints.tsx에 정의된 로그인, 로그아웃 endpoint 값 변경
Relates to #101

Refactor: 로그인, 로그아웃 엔드포인트 상수값 변경

---

fe/play-baseball-fe/pages/chat/index.tsx

- 정상적으로 동작은 하나, 컴파일 상 에러가 있는 부분이 있어 배포에 오류가 발생해 이를 수정함
- 🐛 요소 중 ListItem부분 component 부분을 명시함
Closes #104

Fix: 채팅방 요소 중 ListItem 컴파일 에러 수정

---

fe/play-baseball-fe/components/header.tsx
fe/play-baseball-fe/constants/endpoints.tsx
fe/play-baseball-fe/package-lock.json
fe/play-baseball-fe/package.json
fe/play-baseball-fe/pages/_app.tsx
fe/play-baseball-fe/pages/login/index.tsx

모든 페이지에 공통으로 사용할 header 부분 레이아웃 제작
- 💄 Header 레이아웃 제작
Relates #100
로그인이 저장된 쿠키가 HttpOnly로 되어 있어 Client에서로그인 상태를 js로 자체적인 확인이 불가능합니다.

Feat: 헤더 레이아웃 제작

---

fe/play-baseball-fe/pages/signup/index.tsx

코드의 통일성을 위해 fetch 사용하던 부분을 axios로 변경합니다.
- ♻️ 회원가입 페이지 fetch 부분 axios로 변경
Relates to #112

#112 Refactor: 회원가입 페이지 fetch -> axios 변경

---

src/main/java/org/example/spring/security/config/SecurityConfig.java

BE 접근 시 /login으로 무한 요청을 보내는 문제를 해결하고자 기능을 추가합니다.
- 🐛 오류로 예상되는 api 주소에 대해 url을 명시합니다.
Relates #116

#116 Fix: BE에서 오류나지 않도록 특정 api url 명시

---

build.gradle
src/main/java/org/example/spring/security/filter/RateLimitFilter.java
src/main/java/org/example/spring/security/service/RateLimiterService.java

이 PR은 RateLimitFilter와 RateLimiterService의 성능 개선 및 기능 강화를 목적으로 합니다. Caffeine 캐시 도입, IP 주소 추출 로직 개선 했습니다
- ⚡️ RateLimiterService에 Caffeine 캐시 도입으로 성능 최적화
- ♻️ RateLimitFilter 코드 구조 개선 및 기능 강화
- 🐛 클라이언트 IP 주소 추출 로직 개선 (X-Forwarded-For 헤더 지원)
- 🔧 ObjectMapper를 의존성 주입으로 변경하여 재사용성 향상
- 🗑️ 불필요한 로깅 제거로 성능 최적화
Closes #115 
1. Caffeine 캐시 설정(만료 시간 등)이 적절한지 리뷰 부탁드립니다.
2. X-Forwarded-For 헤더 처리 로직이 보안적으로 안전한지 확인 부탁드립니다.
3. 성능 테스트를 통해 실제 개선 효과를 측정해볼 필요가 있을 것 같습니다.

Refactor: Rate Limit 성능 최적화 및 캐싱 도입

---

fe/play-baseball-fe/constants/endpoints.tsx

임시 도메인 적용에 따라 FE에 정의된 서버 주소 및 요청할 api 주소를 변경합니다
- ♻️ constants.tsx에 정의된 url 값 적용된 도메인에 맞게 변경
#Relates to #121

Refactor: FE에 정의된 서버 URL과 요청할 api url 값 변경

---

src/main/java/org/example/spring/security/config/SecurityConfig.java

- ✨ (새 기능)
- 🐛 (버그 수정)
- ♻️ (리팩토링)
- 📚 (문서 업데이트)
- 🔧 (설정 파일 수정)
- ⚡️ (성능 개선)

Fix: Cors Origin url 추가

---

src/main/java/org/example/spring/security/config/SecurityConfig.java

- ✨ (새 기능)
- 🐛 (버그 수정)
- ♻️ (리팩토링)
- 📚 (문서 업데이트)
- 🔧 (설정 파일 수정)
- ⚡️ (성능 개선)

Fix: SecurityConfig failureUrl 삭제

---

src/main/java/org/example/spring/security/config/SecurityConfig.java

- ✨ (새 기능)
- 🐛 (버그 수정)
- ♻️ (리팩토링)
- 📚 (문서 업데이트)
- 🔧 (설정 파일 수정)
- ⚡️ (성능 개선)

Fix: SecurityConfig 임시 홈 경로 모두 공해

---

src/main/java/org/example/spring/security/service/RateLimiterService.java

RateLimit 관련 코드 리펙터링
- ♻️ 인증된 사용자와 인증되지 않은 사용자를 구분하는 대신, 토큰의 유효성 여부로 구분하고 있습니다.
토큰이 유효한 경우 사용자 이메일을, 그렇지 않은 경우 IP 주소와 User-Agent 정보를 사용하여 rate limit 키를 생성합니다.
하나의 공동 rate limit 버킷을 관리하며, 버킷 생성 시 토큰 유효성 여부에 따라 적절한 버킷 용량 설정.
Relates to #115

Refactor: RateLimit 관련 코드 리펙터링

---

src/main/java/org/example/spring/security/config/SecurityConfig.java

- ✨ (새 기능)
- 🐛 (버그 수정)
- ♻️ (리팩토링)
- 📚 (문서 업데이트)
- 🔧 (설정 파일 수정)
- ⚡️ (성능 개선)

Fix: SecurityConfig "/" 경로 모두 허용

---

src/main/resources/application.yml

기존 이슈에서 리디렉션 관련 내용을 계속 수정합니다.
- 🐛 yml에 헤더 검사하는 내용 추가
Relates to #131

#131 Fix: 무한 리디렉션 관련 해결을 위한 yml 헤더 검사내용 추가

---

src/main/java/org/example/spring/security/config/SecurityConfig.java

SecurityConfig Caddy 사용으로 requiresChannel 제거
SecurityConfig Caddy 사용으로 requiresChannel 제거
- 🐛 SecurityConfig Caddy 사용으로 requiresChannel 제거

Fix: SecurityConfig Caddy 사용으로 requiresChannel 제거

---

src/main/java/org/example/spring/controller/MessageController.java
src/main/java/org/example/spring/domain/message/messageDto/PageResponseDto.java
src/main/java/org/example/spring/domain/message/messageDto/ResponseDto.java
src/main/java/org/example/spring/service/MessageService.java

메시지 컨트롤러 코드 구현
메시지 컨트롤러 코드 구현
- ✨ (새 기능)
- 🐛 (버그 수정)
- ♻️ (리팩토링)
- 📚 (문서 업데이트)
- 🔧 (설정 파일 수정)
- ⚡️ (성능 개선)

Feat: 메시지 컨트롤 코드 추가 

---

fe/play-baseball-fe/constants/endpoints.tsx

FE에서 BE에 URL 요청 시 /api가 누락된 부분을 수정했습니다.
- 🐛 endpoints 요청 부분 수정
Relates to #131

Fix: endpoints url 누락 부분 수정

---

src/main/java/org/example/spring/security/config/SecurityConfig.java
src/main/java/org/example/spring/security/filter/JwtValidatorFilter.java

공개 api jwt 검증 예외 설정 및 Cors 허용 헤더 추가
- 🐛 공개 api jwt 검증 예외 설정 및 Cors 허용 헤더 추가

Fix: 공개 api jwt 검증 예외 설정 및 Cors 허용 헤더 추가

---

src/main/java/org/example/spring/security/config/SecurityConfig.java

- ✨ (새 기능)
- 🐛 (버그 수정)
- ♻️ (리팩토링)
- 📚 (문서 업데이트)
- 🔧 (설정 파일 수정)
- ⚡️ (성능 개선)

#131 Fix: AllowedOrigins 내용에 http 추가

---

src/main/java/org/example/spring/security/config/SecurityConfig.java

- ✨ (새 기능)
- 🐛 (버그 수정)
- ♻️ (리팩토링)
- 📚 (문서 업데이트)
- 🔧 (설정 파일 수정)
- ⚡️ (성능 개선)

#131 Fix: springconfig http.headers 내용 변경

---

src/main/java/org/example/spring/security/config/SecurityConfig.java

이전 commit 내용에 compile error를 수정합니다

#131 Fix: headers compile error

---

src/main/java/org/example/spring/security/config/SecurityConfig.java

현재 존재하는 https 통신 관련 에러를 수정하기 위해 작성한 문서입니다.
- 🐛 setAllowedMethods 내용에 OPTIONS를 추가했습니다.

Fix:  setAllowedMethods 내용에 OPTIONS 추가

---

src/main/resources/application.yml

- ✨ (새 기능)
- 🐛 (버그 수정)
- ♻️ (리팩토링)
- 📚 (문서 업데이트)
- 🔧 (설정 파일 수정)
- ⚡️ (성능 개선)

#131 Fix: application.yml debug 내용 추가

---

fe/play-baseball-fe/pages/login/index.tsx
fe/play-baseball-fe/pages/signup/index.tsx
src/main/java/org/example/spring/security/config/SecurityConfig.java

https 통신 관련 있던 문제사항이 최종 정상화되었습니다.
- http -> https -> http ... 무한 리디렉션
- 페이지 1번 요청이 아닌 무한 요청
- api 요청 시 Spring까지 요청이 가지 않고 Caddy에서 거부
- api 요청 시 Spring까지 간헐적으로 요청이 되는 현상
- 200을 응답했음에도 CORS 문제 발생
- 그 외 기타 등등..
공유가 되면 좋을 것 같아 이번 내용 뿐 아니라 해결하면서 기억나는 부분을 리스트로 작성합니다.
- ✨ application.yml 내용 추가
- - server forward-headers-strategy
- - tomcat remote-ip-header
- - tomcat protocol-header
- 🐛 BE Caddy에서 ssl 관련 검증 로직 삭제
- 🐛 FE Caddy에서 ssl 관련 검증 로직 삭제
- 🐛 CaddyFile "domain/" 부분을 "domain"으로 변경
- 🐛 CaddyFile "domain/" 부분을 "domain"으로 변경
- ♻️ SecurityConfig AllowedOrigins 부분 FE 서버 도메인으로 한정
- ♻️ SecurityConfig AllowedMethods 부분 OPTIONS 추가
아래 스크린샷 참고
Relates to #131
- SecurityConfig 내용이 conflict 날 수 있습니다. 현재 pr 기준 내용 변경이 크지 않으니 확인 부탁드립니다.
- FE에서 axios를 통한 요청을 보낼 때 withCredentials = true 값이 필요합니다.

Fix: https 통신 정상화

---

src/test/java/org/example/spring/controller/AuthControllerTest.java
src/test/java/org/example/spring/repository/MemberRepositoryTest.java
src/test/java/org/example/spring/security/service/AuthServiceTest.java

- ✨ 로그인 테스트 작성
- ✨ 로그아웃 테스트 작성
- ♻️ MemberRepositoryTest findAll PageRequest 조건 추가
Closes #147

Test: 로그인 로그아웃 테스트 작성

---

build.gradle
src/main/java/org/example/spring/config/SwaggerConfig.java
src/main/java/org/example/spring/config/WebSocketConfig.java
src/main/java/org/example/spring/controller/MessageController.java
src/main/java/org/example/spring/security/config/SecurityConfig.java
src/main/java/org/example/spring/security/config/SecurityDevConfig.java

메시지 컨트롤러 스웨거 문서 작성
메시지 컨트롤러 스웨거 문서 작성
- ✨ (새 기능)
- 🐛 (버그 수정)
- ♻️ (리팩토링)
- 📚 (문서 업데이트)
- 🔧 (설정 파일 수정)
- ⚡️ (성능 개선)

Feat: 메시지 컨트롤러 스웨거 문서 작성

---

.github/workflows/Spring CD.yml

- 🔧 Gradle 캐시를 사용하여 빌드 시간 단축
- 🔧 빌드와 배포를 하나의 job으로 통합하여 아티팩트 업로드/다운로드 과정 제거
- 🔧 테스트를 제외한 빌드 실행 (-x test)으로 빌드 시간 단축
- 🔧 Java 프로세스 종료 시 좀 더 안전한 방식 사용

Chore: Update Spring CD.yml

---

.github/workflows/Spring CI.yml

- 🔧 ./gradlew build test --info를 실행하여 빌드와 테스트를 수행합니다.
- 🔧  테스트가 실패하면, 실패한 테스트의 클래스 이름을 build/test-results/test/ 디렉토리에서 TEST-*.xml 파일을 검색하여 추출합니다. 실패한 테스트만 -Dtest.single 옵션을 사용하여 지정하고, -Dtest.debug 옵션을 추가하여 디버그 로깅을 활성화한 상태로 테스트를 다시 실행합니다.

Chore: Update Spring CI.yml

---

fe/play-baseball-fe/components/header.tsx
fe/play-baseball-fe/pages/login/index.tsx

하단 관련 이슈에 따른 버그 내용을 수정했습니다.
- 🐛 로그아웃 요청 시 withCredentials 내용 추가
- 🐛 로그인 요청 시 Authorization을 LocalStorage에 저장 후 100ms 뒤에 router를 통해 페이지 이동하도록 수정
#Relates to #150

Fix: 로그아웃 API 정상화, 로그인 후 페이지 이동 시 header 부분에 반영이 되어있지 않던 점 수정

---

src/main/java/org/example/spring/controller/MessageController.java
src/main/java/org/example/spring/service/MessageService.java

- 엔드포인트 멤버 아이디 삭제
- 헤더에서 토큰 추출 후 토큰으로 멤버 아이디 추출
- 엔드포인트 멤버 아이디 삭제
- 헤더에서 토큰 추출 후 토큰으로 멤버 아이디 추출
- ✨ (새 기능)
- 🐛 (버그 수정)
- ♻️ (리팩토링)
- 📚 (문서 업데이트)
- 🔧 (설정 파일 수정)
- ⚡️ (성능 개선)

Refactor: 메시지 토큰 회원 추출 방식으로 수정

---

src/main/java/org/example/spring/domain/member/dto/LoginResponseDto.java
src/main/java/org/example/spring/security/filter/JwtValidatorFilter.java
src/main/java/org/example/spring/security/filter/RateLimitFilter.java
src/main/java/org/example/spring/security/jwt/JwtTokenValidator.java
src/main/java/org/example/spring/security/jwt/JwtUtils.java
src/main/java/org/example/spring/security/service/AuthService.java
src/main/java/org/example/spring/security/service/JwtAuthenticationService.java
src/test/java/org/example/spring/security/service/AuthServiceTest.java

UsenamePasswordAuthenticationToken 관련 전반적인 코드 리펙터링
- ✨ JwtUtils 의 토큰 추출 로직 분리
- 🐛 예외 처리 로직 개선 및 에러 응답 포맷 통일
- ♻️ filterChain.doFilter() 호출 위치 변경으로 인증 실패 시 요청 중단
- 🔧 불필요한 코드 제거 및 간소화
- ⚡️ 로깅 메시지 개선으로 디버깅 용이성 향상
- ♻️ processToken 및 createAuthenticationFromUserDetails 로직 수정
- ♻️ 사용자 유효성 검사를 위한 UserDetailsService 통합 추가
- ✨ 토큰에서 사용자 정보 검색을 위한 새로운 메서드 getUserDetails 구현
- ✨ 오류 처리 개선을 위한 InvalidTokenException 도입
- ♻️ HTTP 요청에서 JWT를 구문 분석하는 extractTokenFromHeader 메서드 JwtTokenValidator
- ♻️ 유효성 검사 메서드를 리팩터링하여 클레임 대신 부울을 반환
- ♻️ isTokenNotExpired 메서드로 토큰 만료 검사 개선
- ✨ 코드 문서화를 위한 JavaDoc 주석 개선
- ♻️ isTokenBlacklisted 및 addToBlacklist 메서드 최적화
- 📚추적성 향상을 위한 디버그 로깅 추가
Closes #154  (JWT 토큰 검증 프로세스 개선)
JwtTokenValidator와 JwtAuthenticationService 클래스의 변경에 따른 JwtValidatorFilter의 수정사항입니다. 특히 에러 처리 부분과 토큰 추출 …

Refactor: UsenamePasswordAuthenticationToken 관련 전반적인 코드 리펙터링

---

.github/workflows/Spring CD.yml

chmod +x ./gradlew 내용을 추가했습니다.
- 🐛 cd yml에  build 쓰기 권한 추가
#Rel

Update Spring CD.yml

---

src/main/java/org/example/spring/security/config/SecurityConfig.java
src/main/java/org/example/spring/security/config/SecurityDevConfig.java
src/main/java/org/example/spring/security/filter/JwtValidatorFilter.java

- 🐛 shouldNotFilter 메서드에 review, exchage 엔드포인트 제거 및 스웨거 관련 엔드포인트 추가
- 🐛 contentSecurityPolicy 정책 완화

Fix: 스웨거 contentSecurityPolicy 관련 오류 수정 및 review, exchanges 401 에러 수정

---

src/main/java/org/example/spring/common/GlobalExceptionHandler.java
src/main/java/org/example/spring/security/config/SecurityConfig.java
src/main/java/org/example/spring/security/config/SecurityDevConfig.java
src/main/java/org/example/spring/security/jwt/JwtTokenProvider.java
src/main/java/org/example/spring/security/jwt/JwtTokenValidator.java
src/main/java/org/example/spring/security/utils/JwtUtils.java
src/main/java/org/example/spring/service/MessageService.java

JwtTokenValidator 토큰의 유효성을 검사하고 멤버를 반환하는 validateTokenAndGetMember 메서드 추가
- ✨ JwtTokenValidator 토큰의 유효성을 검사하고 멤버를 반환하는 validateTokenAndGetMember 메서드 추가

Feat: JwtTokenValidator validateTokenAndGetMember 메서드 추가

---

src/main/java/org/example/spring/common/GlobalExceptionHandler.java
src/main/java/org/example/spring/constants/RateLimitBucketConstants.java
src/main/java/org/example/spring/controller/AuthController.java
src/main/java/org/example/spring/controller/MemberController.java
src/main/java/org/example/spring/domain/member/Member.java
src/main/java/org/example/spring/exception/AccountBannedException.java
src/main/java/org/example/spring/exception/AccountDeletedException.java
src/main/java/org/example/spring/security/config/SecurityConfig.java
src/main/java/org/example/spring/security/config/SecurityDevConfig.java
src/main/java/org/example/spring/security/filter/JwtValidatorFilter.java
src/main/java/org/example/spring/security/filter/MemberStatusCheckFilter.java
src/main/java/org/example/spring/security/filter/RateLimitFilter.java
src/main/java/org/example/spring/security/jwt/CookieService.java
src/main/java/org/example/spring/security/jwt/JwtTokenValidator.java
src/main/java/org/example/spring/security/service/AuthService.java
src/main/java/org/example/spring/security/service/IpChangeDetectionService.java
src/main/java/org/example/spring/security/service/JwtAuthenticationService.java
src/main/java/org/example/spring/security/utils/AuthUtils.java
src/main/java/org/example/spring/service/AuthService.java
src/main/java/org/example/spring/service/MemberService.java

회원 탈퇴 기능 구현 및 탈퇴된 회원 및 밴된 회원 검증 로직 및 액세스토큰, 리프레시토큰 비교 검증로직 구현
- ✨ 회원 탈퇴 엔드포인트 및 서비스 작성
- ✨ 커스텀 예외 추가
- ✨ 탈퇴된 회원 밴된 회원 처리
- ✨ 액세스토큰, 리프레시토큰 검증로직구현
- 그 외 전반적인 리펙터링
Relates to #128

Feat: 회원 탈퇴 기능 구현

---

src/main/java/org/example/spring/common/GlobalExceptionHandler.java
src/main/java/org/example/spring/security/filter/JwtValidatorFilter.java
src/main/java/org/example/spring/security/filter/MemberStatusCheckFilter.java
src/main/java/org/example/spring/security/jwt/JwtTokenValidator.java
src/main/java/org/example/spring/security/service/JwtAuthenticationService.java

액세스 토큰 재발급 시 응답 메세지 개선
- ✨ 리프레시토큰으로 액세스토큰 재발급시 바로 응답본문에 메세지 추가
- ♻️ 전체 적으로 불필요한 예외처리 제거

Refactor: 액세스 토큰 재발급 시 응답 메세지 개선

---

src/main/java/org/example/spring/controller/ReviewController.java
src/main/java/org/example/spring/domain/review/Review.java
src/main/java/org/example/spring/domain/review/dto/CreateReviewRequest.java
src/main/java/org/example/spring/service/ReviewService.java

리뷰 등록 및 수정 시 권한 확인
- ♻️ 리뷰 등록 시 인증된 사용자 여부 확인, 리뷰 작성자 본인 여부 확인 추가
- ♻️ 리뷰 수정 시 인증된 사용자 여부 확인, 리뷰 작성자 본인 여부 확인 추가
- ♻️ 내가 작성한 리뷰 조회 시 인증된 사용자 여부 확인 추가
- ♻️ 리뷰 이미지 삭제 시 인증된 사용자 여부 확인, 리뷰 작성자 본인 여부 확인 추가
Closes #174

Refactor: 리뷰 등록 및 수정 시 권한 확인

---

src/main/java/org/example/spring/security/filter/JwtValidatorFilter.java
src/main/java/org/example/spring/security/jwt/JwtTokenValidator.java
src/main/java/org/example/spring/security/service/AccountManagementService.java
src/main/java/org/example/spring/security/service/TokenBlacklistService.java
src/main/java/org/example/spring/service/AuthService.java
src/main/java/org/example/spring/service/MemberService.java
src/test/java/org/example/spring/service/MemberServiceTest.java

JwtValidatorFilter 리펙터링
- ♻️ JwtValidatorFilter 리펙터링
- ♻️ TokenBlacklistService 
- ♻️ AccountManagementService
Closes #178

Refactor: JwtValidatorFilter 리펙터링

---

.github/workflows/Spring CD.yml

- 🔧 환경변수를 깃허브 액션에서 전달하는 방식으로 변경 했습니다.

Chore: CD workflow 수정

---

src/main/resources/application-prod.yml

배포시 자동으로 환경변수를 읽기 위한 설정 추가
- ✨ (새 기능)
- 🐛 (버그 수정)
- ♻️ (리팩토링)
- 📚 (문서 업데이트)
- 🔧 (설정 파일 수정)
- ⚡️ (성능 개선)

Chore: application-prod.yml 설정 추가

---

.github/workflows/Spring CD.yml

- ✨ (새 기능)
- 🐛 (버그 수정)
- ♻️ (리팩토링)
- 📚 (문서 업데이트)
- 🔧 (설정 파일 수정)
- ⚡️ (성능 개선)

Chore: Spring CD.yml update

---

src/main/resources/application-prod.yml

- ✨ (새 기능)
- 🐛 (버그 수정)
- ♻️ (리팩토링)
- 📚 (문서 업데이트)
- 🔧 (설정 파일 수정)
- ⚡️ (성능 개선)

Chore: application-prod.yml update

---

src/main/java/org/example/spring/common/GlobalExceptionHandler.java
src/main/java/org/example/spring/security/filter/JwtValidatorFilter.java

메인 페이지 jwt 필터 제외 및 GlobalExceptionHandler 로깅 수정
메인 페이지 jwt 필터 제외 및 GlobalExceptionHandler 로깅 수정
- ♻️ 메인 페이지 jwt 필터 제외("/)
- ♻️ GlobalExceptionHandler 로깅 수정
Closes #192

Refatctor: 메인 페이지 jwt 필터 제외 및 GlobalExceptionHandler 로깅 수정

---

fe/play-baseball-fe/pages/exchange/[id].tsx

Merge 이후 게시물 상세 페이지 영역에 충돌로 인한 컴파일 오류를 수정합니다.
- 🐛 게시물 상세 페이지 조회 코드 정상화
Relates to #196

Fix: 게시물 조회 상세 페이지 충돌 수정

---

.github/workflows/Spring CD.yml
src/main/java/org/example/spring/security/filter/JwtValidatorFilter.java
src/main/java/org/example/spring/security/filter/MemberStatusCheckFilter.java

- 🐛 공개 엔드포인트 필터 처리에 favicon 추가
Closes #198

Fix: BE CD Deloy 명령어 수정 및 공개 엔드포인트 필터 스킵 처리

---

.github/workflows/Spring CD.yml

- ✨ (새 기능)
- 🐛 (버그 수정)
- ♻️ (리팩토링)
- 📚 (문서 업데이트)
- 🔧 (설정 파일 수정)
- ⚡️ (성능 개선)

Fix: BE CD 명령어 수정

---

.github/workflows/Spring CD.yml
build.gradle

- ✨ (새 기능)
- 🐛 (버그 수정)
- ♻️ (리팩토링)
- 📚 (문서 업데이트)
- 🔧 (설정 파일 수정)
- ⚡️ (성능 개선)

Feat: 의존성 추가 및 CD workflow 수정

---

fe/play-baseball-fe/pages/exchange/[id].tsx
fe/play-baseball-fe/pages/exchange/write/[id].tsx
fe/play-baseball-fe/pages/exchange/write/index.tsx
src/main/java/org/example/spring/controller/ExchangeController.java
src/main/java/org/example/spring/domain/exchange/dto/ExchangeDetailResponseDto.java
src/main/java/org/example/spring/domain/exchange/dto/ExchangeNavigationResponseDto.java
src/main/java/org/example/spring/repository/ExchangeRepository.java
src/main/java/org/example/spring/service/ExchangeService.java

- ✨ 실제 데이터 연동하여 상세 페이지 로딩 기능 작업
- ✨ 글 수정 페이지 진입 시 기존 글 내용 로딩되도록 작업
- 🐛 작성자 확인 부분을 boolean으로 전송하여 클라이언트에서 정상적으로 받지 못하는 부분 수정
- 🐛 Lazy 로딩 방식으로 인한 작성자를 정상적으로 불러오지 못하는 부분 수정
- 🐛 게시글 상세조회 링크 정상화
Relates to #204
수정 부분에 이미지 관련 사안은 업데이트 필요

Feat: 게시물 상세 조회 실제 데이터 연동 작업

---

fe/play-baseball-fe/components/UserProfile.tsx
fe/play-baseball-fe/pages/_app.tsx
fe/play-baseball-fe/pages/exchange/[id].tsx

CD에서 에러를 발생시키는 FE 영역 관련 Build 에러 영역을 수정합니다.
- 🐛 UserProfile.tsx 이벤트 핸들러 e 타입 명시
- 🐛 _app.tsx header import 소문자로 변경
- 🐛 게시물 상세 조회 tsx response 타입 명시

Fix: FE 영역 빌드 에러 문제 수정

---

src/main/java/org/example/spring/constants/SalesStatus.java
src/main/java/org/example/spring/controller/ExchangeController.java
src/main/java/org/example/spring/domain/exchange/Exchange.java
src/main/java/org/example/spring/domain/exchange/dto/ExchangeAddRequestDto.java
src/main/java/org/example/spring/domain/exchange/dto/ExchangeDetailResponseDto.java
src/main/java/org/example/spring/domain/exchange/dto/ExchangeModifyRequestDto.java
src/main/java/org/example/spring/domain/exchange/dto/ExchangeNavigationResponseDto.java
src/main/java/org/example/spring/domain/exchange/dto/ExchangeResponseDto.java
src/main/java/org/example/spring/domain/exchangeImage/ExchangeImage.java
src/main/java/org/example/spring/domain/exchangeImage/dto/ExchangeImageResponseDto.java
src/main/java/org/example/spring/repository/ExchangeImageRepository.java
src/main/java/org/example/spring/repository/ExchangeRepository.java
src/main/java/org/example/spring/service/ExchangeImageService.java
src/main/java/org/example/spring/service/ExchangeService.java

현재 Exchange 관련 코딩 컨벤션이 지켜지지 않아 이를 수정합니다.
- ♻️ Exchange 관련 모든 클래스 코딩 컨벤션 업데이트
Relates to #209

Refactor: Exchange 관련 BE 코드 모두 naver style 적용

---

.github/workflows/Spring CD.yml
.github/workflows/Spring CI.yml
build.gradle
fe/play-baseball-fe/next.config.mjs
src/main/java/org/example/spring/config/S3Config.java
src/main/java/org/example/spring/service/ExchangeService.java
src/main/java/org/example/spring/service/S3Service.java
src/main/resources/application-prod.yml

현재 시스템 상 이미지 관리 스토리지가 존재하지 않고, BE에 리소스 배치 시 접근 권한 등의 문제가 있어 이를 관리하기 위한 시스템을 새로 작성합니다.
- ✨ AWS S3 스토리지가 추가되었습니다.
- ✨ S3 스토리지 관리에 사용할 S3Config, S3Service 코드가 추가되었습니다.
- ♻️ ExchangeService의 이미지 관리 부분이 S3Service에 통합되었습니다.
- 📚 S3 인스턴스가 생기면서 환경 변수가 추가로 생겼으니 문서를 확인해주세요.
- 🔧 build.gradle에 S3 관련 의존성이 추가되었습니다.
Relates to #211

Feat: AWS S3 스토리지를 이용한 이미지 관리 기능 제작

---

src/main/java/org/example/spring/domain/exchange/dto/ExchangeDetailResponseDto.java
src/main/java/org/example/spring/repository/ReviewOverviewRepository.java
src/main/java/org/example/spring/service/ExchangeService.java

중고 거래 게시물 상세 조회 시 작성자의 평점과 리뷰 총개수 표시 및 Review가 없는 Member의 ReviewOverview 조회 시 처리
- ♻️ 중고 거래 게시물 상세 조회 시 작성자의 평점과 리뷰 총개수 표시
- ♻️ Review가 없는 Member의 ReviewOverview 조회 시 디폴트 값 처리
Closes #216

Refactor: 중고 거래 게시물 상세 조회 시 작성자의 평점과 리뷰 총개수 표시

---

src/main/java/org/example/spring/service/ExchangeService.java
src/main/java/org/example/spring/service/ReviewService.java
src/main/java/org/example/spring/service/S3Service.java

현재 Service Layer에서 이미지 업로드, 삭제 관련 메서드가 파편화되어있어 이를 통합하는 작업을 진행했습니다.
- ✨ S3Service 파일 삭제 로직 추가
- ♻️ ExchangeService Modify 메서드 S3Service 사용하도록 변경
- ♻️ ReviewService 이미지 관련 메서드 S3Service 사용하도록 변경
- 📚 S3Service JavaDoc 작성
Relates to #218

Refactor: 이미지 관련 Service 메서드 로직 통합

---

build.gradle

S3 충돌 관련 이슈를 해결합니다.
- 🔧 build.gradle 의존성 일부 제거
Relates to #221

#221 Fix: s3 충돌문제 관련 의존성 수정

---

src/main/java/org/example/spring/security/filter/JwtValidatorFilter.java

- ✨ (새 기능)
- 🐛 (버그 수정)
- ♻️ (리팩토링)
- 📚 (문서 업데이트)
- 🔧 (설정 파일 수정)
- ⚡️ (성능 개선)

Fix: JwtValidatorFilter shouldNotFilter 경로 추가

---

build.gradle

- ✨ (새 기능)
- 🐛 (버그 수정)
- ♻️ (리팩토링)
- 📚 (문서 업데이트)
- 🔧 (설정 파일 수정)
- ⚡️ (성능 개선)

Chore: build.gradle 잠재 충돌 위험 제거

---

src/main/java/org/example/spring/controller/ExchangeLikeController.java
src/main/java/org/example/spring/domain/like/ExchangeLike.java
src/main/java/org/example/spring/domain/like/dto/AddLikeRequest.java
src/main/java/org/example/spring/repository/ExchangeLikeRepository.java
src/main/java/org/example/spring/service/ExchangeLikeService.java

중고 거래 게시글에 대한 좋아요 기능 구현
- ✨ 좋아요 추가
- ✨ 좋아요 취소
Closes #215

Feat: 중고 거래 게시글에 대한 좋아요 기능 구현

---

.github/workflows/FE CD.yml
.github/workflows/Spring CD.yml

- ✨ (새 기능)
- 🐛 (버그 수정)
- ♻️ (리팩토링)
- 📚 (문서 업데이트)
- 🔧 (설정 파일 수정)
- ⚡️ (성능 개선)

Chore: BE FE CD workflow 수정

---

src/main/java/org/example/spring/domain/like/ExchangeLike.java
src/main/java/org/example/spring/domain/likeOverview/LikeOverview.java
src/main/java/org/example/spring/repository/ExchangeLikeRepository.java
src/main/java/org/example/spring/repository/LikeOverviewRepository.java
src/main/java/org/example/spring/service/ExchangeLikeService.java
src/main/java/org/example/spring/service/LikeOverviewService.java

LikeOverview 구현
- ✨ Exchange별 좋아요 개수를 확인할 수 있는 LikeOverview 구현
- ♻️ 좋아요 취소 시 좋아요 개수를 감소시키기 위해 ExchangeLike에 canceledAt 필드 추가
Closes #229

Feat: LikeOverview 구현

---

fe/play-baseball-fe/package-lock.json
fe/play-baseball-fe/package.json
fe/play-baseball-fe/pages/exchange/[id].tsx
fe/play-baseball-fe/pages/exchange/write/[id].tsx
fe/play-baseball-fe/pages/exchange/write/index.tsx
fe/play-baseball-fe/pages/index.tsx
src/main/java/org/example/spring/constants/SalesStatus.java
src/main/java/org/example/spring/controller/ExchangeController.java
src/main/java/org/example/spring/domain/exchange/Exchange.java
src/main/java/org/example/spring/domain/exchange/dto/ExchangeNavigationResponseDto.java
src/main/java/org/example/spring/domain/exchange/dto/ExchangeResponseDto.java
src/main/java/org/example/spring/repository/ExchangeRepository.java
src/main/java/org/example/spring/service/ExchangeService.java

프론트 페이지 디자인 전반과 버그 등을 수정하고 기능 추가 및 관련 BE 코드를 수정했습니다.
- ✨ 게시물 상세 페이지에 회원의 리뷰, 평점을 볼 수 있도록 기능이 추가되었습니다.
- ✨ 게시물 상세 페이지 진입 시 조회수가 업데이트 되도록 기능이 추가되었습니다.
- ✨ 전체 글 조회 영역에 판매 상태에 따른 필터링 기능이 추가되었습니다.
- 🐛 게시물 작성 시 라우팅이 잘못 설정되어있던 이슈를 해결했습니다.
- 🐛 게시물 작성, 수정 시 이미지를 첨부하지 않을 경우 글이 작성되지 않던 문제를 해결했습니다.
- ♻️ SalesStatus에 NONE 값을 추가했습니다.
- 💄 메인 페이지 디자인이 업데이트 되었습니다.
- 🔧 FE 영역에 qs 패키지를 추가로 설치했습니다.
Realtes to #231

Feat: 메인 페이지 디자인 전반, 글 삭제, 수정 버그 수정, 

---

fe/play-baseball-fe/components/header.tsx
fe/play-baseball-fe/constants/endpoints.tsx

window.location.href 오류 로 router.push 로 변경
- ✨ (새 기능)
- 🐛 (버그 수정)
- ♻️ (리팩토링)
- 📚 (문서 업데이트)
- 🔧 (설정 파일 수정)
- ⚡️ (성능 개선)

Fix: header.tsx 오류 수정

---

src/main/java/org/example/spring/security/filter/MemberStatusCheckFilter.java

- ✨ (새 기능)
- 🐛 (버그 수정)
- ♻️ (리팩토링)
- 📚 (문서 업데이트)
- 🔧 (설정 파일 수정)
- ⚡️ (성능 개선)

Refactor: MemberStatusCheckFilter 경로 변경

---

src/main/java/org/example/spring/controller/ExchangeLikeController.java
src/main/java/org/example/spring/service/ExchangeLikeService.java

ExchangeLikeController, ExchangeLikeService의 addLike 반환 타입 변경
- ♻️ ExchangeLikeController의 addLike 반환 타입 변경
- ♻️ ExchangeLikeService의 addLike 반환 타입 변경
Closes #238

Refactor: ExchangeLikeController, ExchangeLikeService의 addLike 반환 타입 변경

---

src/main/java/org/example/spring/domain/exchange/dto/ExchangeDetailResponseDto.java
src/main/java/org/example/spring/service/ExchangeService.java

중고 거래 게시글 상세 정보에 좋아요 상태 추가
- ♻️ 중고 거래 게시글 상세 정보에 좋아요 상태 추가
Closes #244

Refactor: 중고 거래 게시글 상세 정보에 좋아요 상태 추가

---

src/main/java/org/example/spring/domain/member/dto/MemberResponseDto.java

- ✨ (새 기능)
- 🐛 (버그 수정)
- ♻️ (리팩토링)
- 📚 (문서 업데이트)
- 🔧 (설정 파일 수정)
- ⚡️ (성능 개선)

Refactor: MemberResponseDto 필드 추가

---

.gitignore
fe/play-baseball-fe/components/UserProfile.tsx
fe/play-baseball-fe/pages/member/[id].tsx

TEST to see if empty tsx file is causing CI errors.
- ✨ Add member page implementation
Relates to #172 
N/A

feat: add missing memberpage implementation (test)

---

src/main/java/org/example/spring/security/filter/MemberStatusCheckFilter.java

- ✨ (새 기능)
- 🐛 (버그 수정)
- ♻️ (리팩토링)
- 📚 (문서 업데이트)
- 🔧 (설정 파일 수정)
- ⚡️ (성능 개선)

Feat: MemberStatusCheckFilter 공개 엔드포인트 경로 추가

---

.github/workflows/Spring CI.yml
src/main/java/org/example/spring/controller/ExchangeController.java
src/main/java/org/example/spring/controller/ExchangeLikeController.java
src/main/java/org/example/spring/controller/ReviewController.java

API 명세서 반영을 위해 제목과 관련된 RestController 내용을 업데이트합니다.
- ✨ ExchangeController 내용이 Swagger 문서에 업데이트 되었습니다.
- ✨ ExchangeLikeController 내용이 Swagger 문서에 업데이트 되었습니다.
- ✨ ReviewController 내용이 Swagger 문서에 업데이트 되었습니다.
Relates to #260

Refactor: Exchange, Review, Like Controller Swagger 문서 업데이트

---

fe/play-baseball-fe/pages/member/[id].tsx

See title.
- 🐛 Build 때 에러 수정.
Closes #264 
N/A

Fix: TS error in member/[id] page

---

README.md

See title.
- 📚 update README.md
N/A

Chore: Add CI status badge to README.md

---

README.md
src/main/java/org/example/spring/security/config/SecurityConfig.java
src/main/java/org/example/spring/security/config/SecurityDevConfig.java
src/main/java/org/example/spring/security/filter/JwtValidatorFilter.java
src/main/java/org/example/spring/security/filter/MemberStatusCheckFilter.java

- ✨ (새 기능)
- 🐛 (버그 수정)
- ♻️ (리팩토링)
- 📚 (문서 업데이트)
- 🔧 (설정 파일 수정)
- ⚡️ (성능 개선)

Feat: 잘못된 공개 엔드포인트 처리 수정

---

fe/play-baseball-fe/pages/login/index.tsx
fe/play-baseball-fe/pages/signup/index.tsx

증상은 제목과 동일하며, 해결이 완료되어 PR을 작성합니다.
- 🐛 회원가입 시 성공으로 처리되는 조건이 status 200 -> 201로 변경되었습니다.
- 🐛 이제 서버 주소 환경변수가 존재할 경우 router 이동이 아닌, href를 사용하여 서버 메인 페이지로 강제 이동시킵니다.
Relates to #272

Fix: 회원가입 성공 시 렌더링 오류, 로그인 시 새로고침해야 헤더에 반영되던 버그 수정

---

README.md

- ✨ (새 기능)
- 🐛 (버그 수정)
- ♻️ (리팩토링)
- 📚 (문서 업데이트)
- 🔧 (설정 파일 수정)
- ⚡️ (성능 개선)

Docs: ReadMe 3안

---

README.md

- ✨ (새 기능)
- 🐛 (버그 수정)
- ♻️ (리팩토링)
- 📚 (문서 업데이트)
- 🔧 (설정 파일 수정)
- ⚡️ (성능 개선)

Docs: ReadMe update

---

.github/workflows/FE CD.yml
.github/workflows/Spring CD.yml

배포가 진행될 예정으로 이제 테스트 환경에서 배포가 자동화되지 않도록 변경합니다.
- ♻️ FE, BE CD 내용 main에 push 되었을 때만 동작하도록 변경
Relates to #281

Refactor: 배포 자동화 main으로 한정하도록 변경

---

src/main/java/org/example/spring/controller/MessageController.java
src/main/java/org/example/spring/repository/MemberRepository.java
src/main/java/org/example/spring/repository/message/MessageMemberRepository.java
src/main/java/org/example/spring/service/MessageService.java

메시지룸 참여 회원 조회 기능 추가
메시지룸 참여 회원 조회 기능 추가
- ✨ (새 기능)
- 🐛 (버그 수정)
- ♻️ (리팩토링)
- 📚 (문서 업데이트)
- 🔧 (설정 파일 수정)
- ⚡️ (성능 개선)

Feat: 메시지룸 참여 회원 조회

---

.github/workflows/Spring CD.yml
src/main/resources/application-prod.yml

프로젝트에 채팅이 적용되어 사용되었던 기술인 redis를 배포 환경에서도 정상 작동하도록 이를 수정합니다.
- 🔧 yml 파일에 redis 부분 depth가 변경되었습니다.
- 🔧 BE CD 파일에 redis 관련 환경변수가 추가되었습니다.
Relates to #289

#289 Refactor: CD Redis 적용

---

fe/play-baseball-fe/pages/chat/index.jsx
src/main/java/org/example/spring/config/RedisConfig.java
src/main/java/org/example/spring/domain/message/messageDto/MessageResponseDto.java
src/main/java/org/example/spring/domain/message/messageDto/MessageRoomResponseDto.java
src/main/java/org/example/spring/service/MessageService.java

소켓 주소 수정
소켓 주소 수정
- ✨ (새 기능)
- 🐛 (버그 수정)
- ♻️ (리팩토링)
- 📚 (문서 업데이트)
- 🔧 (설정 파일 수정)
- ⚡️ (성능 개선)

Refactor: 소켓 주소 수정

---

README.md
src/main/java/org/example/spring/controller/AuthController.java
src/main/java/org/example/spring/security/config/MailConfig.java
src/main/java/org/example/spring/security/config/SecurityConfig.java
src/main/java/org/example/spring/security/filter/MemberStatusCheckFilter.java
src/main/java/org/example/spring/security/service/AccountManagementService.java
src/main/java/org/example/spring/security/service/CookieService.java
src/main/java/org/example/spring/security/service/CustomUserDetailsService.java
src/main/java/org/example/spring/security/service/CustomUsernamePasswordAuthenticationProvider.java
src/main/java/org/example/spring/security/service/EmailService.java
src/main/java/org/example/spring/security/service/RateLimiterService.java
src/main/java/org/example/spring/security/service/TokenBlacklistService.java
src/main/java/org/example/spring/security/utils/AuthUtils.java
src/main/java/org/example/spring/security/utils/JwtUtils.java
src/main/java/org/example/spring/service/AuthService.java
src/main/java/org/example/spring/service/MemberService.java
src/test/java/org/example/spring/controller/MemberControllerTest.java
src/test/java/org/example/spring/service/MemberServiceTest.java

- 📚 보안관련 모든 클래스 자바독추가
Closes #247

Docs: 보안관련 클래스 자바독 추가

---

fe/play-baseball-fe/pages/chat/index.jsx

https 로 수정 
https 로 수정 
- ✨ (새 기능)
- 🐛 (버그 수정)
- ♻️ (리팩토링)
- 📚 (문서 업데이트)
- 🔧 (설정 파일 수정)
- ⚡️ (성능 개선)

Feat: https 로 수정 #287

---

fe/play-baseball-fe/components/header.tsx
fe/play-baseball-fe/pages/exchange/[id].tsx
fe/play-baseball-fe/pages/exchange/write/[id].tsx
fe/play-baseball-fe/pages/exchange/write/index.tsx
fe/play-baseball-fe/pages/my/index.tsx

반응 없는 버튼을 활성화합니다.
회원 권한에 따른 오류 발생 방지가 적용된 내용입니다.
- ✨ 마이페이지 수정, 탈퇴 시 페이지 라우팅
- ✨ 헤더 로그인, 홈 버튼 제외 비회원일 시 클릭하면 로그인 페이지로 이동
- ✨ 상세페이지 비회원이 채팅 버튼 클릭 시 로그인 페이지로 이동
- ✨ 상세페이지 결제하기 버튼 Alert로 변경
Relates to #293

Fix: 반응 없는 버튼  반응 활성화, 비회원일 시 회원 전용 페이지 접근 차단 등

---

src/main/java/org/example/spring/service/LikeOverviewService.java
src/test/java/org/example/spring/repository/ReviewRepositoryTest.java

ReviewRepository 테스트 코드 작성, LikeOverview 업데이트 시간 변경
- ♻️ ReviewRepository 테스트 코드 수정
- ♻️ LikeOverview 업데이트 시간 24시간에서 1분으로 변경
Closes #246

Refactor: ReviewRepository 테스트 코드 작성, LikeOverview 업데이트 시간 변경

---

src/main/java/org/example/spring/domain/member/dto/MemberMessageResponseDto.java
src/main/java/org/example/spring/domain/message/messageDto/MessageResponseDto.java

채팅 페이지 진입 시 채팅방 렌더링에 이상이 있던 증상을 해결했습니다.
- 🐛 MessageResponseDto에서 Entity 직접사용 하지 않도록 수정
Relates to #302

Fix: 채팅 500에러 관련 직렬화 문제 수정

---

src/main/java/org/example/spring/service/MessageService.java

닫힌 이슈 관련하여 누락된 파일이 있어 이를 적용합니다.
- 🐛 MessageService에서 특정한 조건에서 Exception을 날리는 오류를 수정함
Close #302

Fix: MessageService 내용 누락하여 재업로드
